[pytest]
addopts =
    -s
    -v
    --headed
    --slowmo=1000
    --html=test-results/report.html
    --screenshot on
    --video retain-on-failure
    --output=log/
    --tracing=on
    --base-url https://www.saucedemo.com
